### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by gopalgoel19**
@aptrishu Don't merge for now. Give reviews only. I will add more commits.

### CODE REVIEW

**Comment by aptrishu** [comment]
ack 6de9c95b90e9d2acef0631ba87e7dc1031111533

**Review by aptrishu — COMMENTED** [review]
can we have different section for each room a user joins?
 a new section or new pop up.. whatever, just that its cluttered on the same page that you have joined this you have joined that ?

**Review by aptrishu — APPROVED** [review]

**Comment by aptrishu** [comment]
unack 6de9c95b90e9d2acef0631ba87e7dc1031111533

**Comment by aptrishu** [comment]
unack ee297a4d356ae091f761660681e3872d36069736

**Comment by gopalgoel19** [comment]
@aptrishu I was thinking to show online members in the current room on the right side. The center part will show conversation texts. And we may implement it in a way that on joining a new room, the user will loose all the previous conversation of the old room. The new room conversation window will start fresh.

**Comment by aptrishu** [comment]
yes, and on the left side we have the rooms and on clicking each room we'll load its conversation in the middle part. one more thing is that if I switch to room2, the conversation in room1 should not be lost and we should not be disconnected automatically without asking. So that I can switch among rooms smoothly.

**Comment by gopalgoel19** [comment]
@aptrishu "if I switch to room2, the conversation in room1 should not be lost" -  On switching room, should I remove the previous conversation and start new or should retain the previous conversation in the conversation window and new conversation texts come below it?

**Comment by aptrishu** [comment]
A room should only contain that part of conversation that has taken place in that very room. when I switch to other room it should show all the conversation in that room after I have joined, or if I'm joining for the first time then just the regular message `this this are already present in this room`.
I think we need to sync a database for this purpose ?

**Comment by gopalgoel19** [comment]
@aptrishu no need for a database. We don't need to store anything long term. So, its good to keep everything in memory. What exactly are you thinking to store in the database?

**Comment by aptrishu** [comment]
chat and user data(if needed in near future).

**Comment by aptrishu** [comment]
Hello @rultor

**Comment by aptrishu** [comment]
hello @rultor

**Comment by aptrishu** [comment]
@rultor merge

**Pull request merged**
