### PR TITLE
Add private room feature issue #1

### PR DESCRIPTION
**Pull request by gopalgoel19**
How to use this feature:
User1 may join a private room with a custom room name, say "Secret". If user2 also uses "Secret" as the name of the private room, he gets connected to the same room in which user1 is present. i.e both user1 and user2 are now in a room named "Secret".

### CODE REVIEW

**Comment by aptrishu** [comment]
Awesome work thanks.
Some of the commits can be squashed into one. It's better to keep atomic commits (means one commit -> one feature). Like if you have a commit `adds a, removes b` and then another commit `adds b`, then you can squash both of them to one commit which will have changes `adds a`.

Also, do you have `coala` installed locally ?

**Comment by aptrishu** [comment]
We have coala to check code formatting in Travis CI so install and run `coala` locally, it'll fix all those errors for you. :)

**Comment by gopalgoel19** [comment]
@aptrishu by squashing commits, you mean to be thoughtful when making commits, right? One feature One commit. Cool. And yes coala. 😉

**Comment by aptrishu** [comment]
Yes, also by squashing I meant https://github.com/blog/2141-squash-your-commits

**Comment by aptrishu** [comment]
You see some of your commits are failing on tests. You need to rectify them.
Also *do not* work on master branch. make a new branch work there , make PR from that branch, get things merged. Then rebase master to fetch new commits from upstream, so that your local master would be equal to your remote's master branch.

**Comment by aptrishu** [comment]
@rultor hello

**Comment by gopalgoel19** [comment]
@devanshu-ghosh aptrishu's last comment is real nice here. Use this method. 👍 
PR from another branch and then rebase your frok's master after PR is accpeted. And yes, coala. 😆

**Pull request closed without merging**
